### PR TITLE
As discussed, replace resolve by resolveonly (no dash for consistency), add noresolve

### PR DESCRIPTION
**Pull request by SjonHortensius**
The noresolve seems to do what I want it to, but could you have an extra look at it?

It is meant primarily for creating a single package (eg. rails), without needing to wait for all dependencies to be created too (because they might already be installed for example)

### CODE REVIEW

**Comment by minad** [comment]
Ok, thx. Can you please update the manpage to reflect all the options too?

**Comment by SjonHortensius** [comment]
So will you complete this pull?

**Comment by minad** [comment]
thx, forgot about this. Sorry

**Comment by SjonHortensius** [comment]
Ah, no problem

**Pull request merged**
